### ISSUE TITLE
Drop z bloków

### ISSUE THREAD

**Issue by grzegorz2047** [grzegorz2047/OpenGuild2047#136]
Wysłać wiadomość jaki drop powstał z bloku; wziąć pod uwagę enchanty (durability, silk touch oraz fortune); zmieniać durability przy dropie, bo nie zmienia się przy event.setCancelled;
Zaprogramować config wg. poniższego przykładu. Stworzyć plik z poniższą konfiguracją.
```
drop:
  enabled: false
  notify-cant-drop-from-not-eligible-block: true
  drop-to-eq: false
  blocks-from-where-item-drops:
    - STONE
  exp:
    enabled: true
    quantity: 1-2
    chance: 0.75
  materials:
    STONE:
      quantity: 2-4
      chance: 0.69
      height: >0<75
      message: "&7Znaleziono: &b[%q] Stone&7!"
      tool:
        - IRON_PICKAXE
        - DIAMOND_PICKAXE
    IRON_ORE:
      quantity: 2-4
      chance: 0.69
      message: "&7Znaleziono: &b[%q] Stone&7!"
```
